name: Cache Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-0f8a790
          restore-keys: |
            cache-0f8a790
      
      - name: prime-cache-0f8a790
        run: |
          if [ "${{ steps.cache.outputs.cache-hit }}" == "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
          fi
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
